plots:
	R -f create_all_or_none.R
	R -f create_multi_agg_chart.R
	R -f create_multi_gb_chart.R
	R -f create_baseline_chart.R
	R -f create_parallel_noop_chart.R
	R -f create_in_memory_chart.R
	R -f create_utility_distribution_chart.R
	R -f create_param_plot.R

